spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker
spring.datasource.username=joshua
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.serialization.write-dates-as-timestamps=false